
// eslint-disable-next-line import/no-absolute-path
import "/styles/globals/globals.scss";
import Head from "next/head";

import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "./misc/navbar";

// chakra UI

function MyApp({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Ten Takeaways</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ChakraProvider>
                <main>
                    <Navbar />

                    <Component {...pageProps} />
                </main>
            </ChakraProvider>
        </>
    );
}

export default MyApp;
